### ISSUE TITLE
Black ores with 24w34a

### ISSUE THREAD

**Issue by Lolothepro** [raspberrygitq/Animated-Ore-Vanilla-Emissive#1]
![2024-08-21_17 45 19](https://github.com/user-attachments/assets/34641e1e-7e02-428e-b6f7-7a22db3c5557)

**Comment by raspberrygitq** [comment]
Fixed, https://github.com/raspberrygitq/Animated-Ore-Vanilla-Emissive/commit/2cecf1bd2ce21e7d1c5c0b91dce5e1a1a06993cc
